# Generated by Django 5.1.3 on 2025-08-09 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConfiguracaoSite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "qr_code_pix",
                    models.ImageField(
                        upload_to="qr_codes/", verbose_name="QR Code PIX"
                    ),
                ),
                (
                    "chave_pix",
                    models.CharField(max_length=255, verbose_name="Chave PIX"),
                ),
                (
                    "nome_beneficiario",
                    models.CharField(
                        max_length=255, verbose_name="Nome do Beneficiário"
                    ),
                ),
            ],
            options={
                "verbose_name": "Configuração do Site",
                "verbose_name_plural": "Configurações do Site",
            },
        ),
    ]
