# Generated by Django 5.1.3 on 2025-05-20 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0013_rename_qrcode_qrcodedoacao_imagem_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="qrcodedoacao",
            name="chave_pix",
        ),
    ]
