# Generated by Django 5.1.3 on 2025-05-20 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0014_remove_qrcodedoacao_chave_pix"),
    ]

    operations = [
        migrations.DeleteModel(
            name="QrCodeDoacao",
        ),
    ]
