# Generated by Django 5.1.3 on 2025-05-20 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0016_qrcode"),
    ]

    operations = [
        migrations.DeleteModel(
            name="QRCode",
        ),
    ]
