# Generated by Django 5.1.3 on 2025-05-20 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0017_delete_qrcode"),
    ]

    operations = [
        migrations.CreateModel(
            name="InstituicaoParceira",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome",
                    models.CharField(
                        max_length=100, verbose_name="Nome da Instituição"
                    ),
                ),
                (
                    "chave_pix",
                    models.CharField(max_length=255, verbose_name="Chave Pix"),
                ),
                (
                    "qr_code",
                    models.ImageField(upload_to="qrcodes/", verbose_name="QR Code"),
                ),
                ("ativo", models.BooleanField(default=True, verbose_name="Ativo")),
                (
                    "ordem",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Ordem de exibição"
                    ),
                ),
            ],
            options={
                "verbose_name": "Instituição Parceira",
                "verbose_name_plural": "Instituições Parceiras",
                "ordering": ["ordem", "nome"],
            },
        ),
        migrations.CreateModel(
            name="InstituicaoPrincipal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome",
                    models.CharField(
                        max_length=100, verbose_name="Nome da Instituição"
                    ),
                ),
                (
                    "chave_pix",
                    models.CharField(max_length=255, verbose_name="Chave Pix"),
                ),
                (
                    "qr_code",
                    models.ImageField(upload_to="qrcodes/", verbose_name="QR Code"),
                ),
                (
                    "descricao",
                    models.CharField(
                        default="Abra o aplicativo do seu banco e escaneie o código acima.",
                        max_length=255,
                        verbose_name="Descrição",
                    ),
                ),
            ],
            options={
                "verbose_name": "Instituição Principal",
                "verbose_name_plural": "Instituição Principal",
            },
        ),
    ]
