# Generated by Django 5.1.3 on 2025-05-20 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0018_instituicaoparceira_instituicaoprincipal"),
    ]

    operations = [
        migrations.DeleteModel(
            name="InstituicaoParceira",
        ),
        migrations.DeleteModel(
            name="InstituicaoPrincipal",
        ),
    ]
