# Generated by Django 5.1.3 on 2025-05-20 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0019_delete_instituicaoparceira_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrganizacaoBeneficente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=255)),
                ("imagem", models.ImageField(upload_to="qrcodes/")),
                ("chave_pix", models.EmailField(max_length=254)),
            ],
        ),
    ]
