# Generated by Django 5.1.3 on 2025-05-20 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0020_organizacaobeneficente"),
    ]

    operations = [
        migrations.DeleteModel(
            name="OrganizacaoBeneficente",
        ),
    ]
