# Generated by Django 5.1.3 on 2025-05-20 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0022_pixqrcode"),
    ]

    operations = [
        migrations.DeleteModel(
            name="PixQRCode",
        ),
    ]
