# Generated by Django 5.1.3 on 2025-05-20 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0024_donationinfo"),
    ]

    operations = [
        migrations.CreateModel(
            name="PixParceiro",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("imagem", models.ImageField(upload_to="qrcodes/")),
                ("chave_pix", models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name="donationinfo",
            name="imagem",
            field=models.ImageField(upload_to="doacao/"),
        ),
    ]
