# Generated by Django 5.1.3 on 2025-06-03 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0025_pixparceiro_alter_donationinfo_imagem"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="donationinfo",
            options={
                "verbose_name": "Pix Principal",
                "verbose_name_plural": "Pix Principal",
            },
        ),
    ]
